<a href="https://colab.research.google.com/github/PriyathamVarma/tensorflow/blob/main/TensorFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This notebook is for tensorflow basics started on 24/12/2021.

In [2]:
# this is for specifing the exact version
%tensorflow_version 1.3.0

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `1.3.0`. This will be interpreted as: `1.x`.


TensorFlow 1.x selected.


In [3]:
# imports
import tensorflow as tf

In [4]:
# Check the version
tf.__version__

'1.15.2'

In [5]:
# Creating a constant in tensorflow
some_random_constant = tf.constant(1.0267560347865345673264276597346598763497569378465987346985763489765)

In [6]:
type(some_random_constant)

tensorflow.python.framework.ops.Tensor

In [7]:
some_random_constant

<tf.Tensor 'Const:0' shape=() dtype=float32>

In [8]:
# Session
tf.Session()

In [9]:
with tf.Session() as sess:
  result = sess.run(some_random_constant)

In [10]:
result

1.026756

# Mathematical operations

In [11]:
a = tf.constant(1)
b = tf.constant(2)

In [12]:
a + b

<tf.Tensor 'add:0' shape=() dtype=int32>

In [13]:
with tf.Session() as sess:
  result_2 = sess.run(a+b)

In [14]:
result_2

3

# Creating matrics

In [15]:
# create a matrix
mat = tf.fill((4,4),10) # create a matrix of 4 * 4 with values 10
zeros = tf.zeros((4,4)) # create a matrix of 4 * 4 with values 0
ones = tf.ones((1,1))   # create a matrix of 1 * 1 with values 1
normal = tf.random_normal((4,4),mean=0,stddev=1.0) # create a matrix with 4 * 4 with a normal distribution values

In [16]:
# operating all
my_ops = [mat,zeros,ones,normal]

In [17]:
my_ops

[<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>,
 <tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'ones:0' shape=(1, 1) dtype=float32>,
 <tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>]

In [18]:
sess = tf.Session()

In [19]:
# Loop through all tesnors
for ops in my_ops:
  print(sess.run(ops))
  print("")

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1.]]

[[ 0.5470118   0.86372006 -0.06877813  1.1141809 ]
 [-0.80387676 -0.45685044  1.0084647   0.08056613]
 [ 0.2846049  -0.7563923   0.8931992   2.0625546 ]
 [ 0.4643452   1.0336391  -0.5029766  -0.56745213]]



In [20]:
# to access individually
req_array = sess.run(my_ops[3])

In [21]:
req_array[2][3]

1.1731607

In [22]:
# Get shape of tesnor
zeros.get_shape()

TensorShape([Dimension(4), Dimension(4)])

# Multiplying two matrices


In [23]:
mutiplication_of_matrices = tf.matmul(normal,normal)

In [24]:
sess.run(mutiplication_of_matrices)

array([[-2.1119545 , -0.6237242 , -1.8805946 ,  1.755933  ],
       [ 0.28616467,  0.12672985,  0.1982871 , -0.17851736],
       [ 1.4243618 ,  0.05374526,  0.59927595,  2.6578357 ],
       [-2.5733588 , -1.4613314 ,  1.5299532 ,  0.86622113]],
      dtype=float32)

# TensorFlow graphs
# <h3 style="color:black">Tensorflow graphs are set of connected nodes(vertices)</h3>
# <h3> The connections are referred to as edges. </h3>
# <h3> Each node can take n no of inputs and give a output <h3>

In [26]:
node_1 = tf.constant(1)

In [27]:
node_2 = tf.constant(2)

In [28]:
node_3 = node_1 + node_2

In [29]:
sess.run(node_3)

3

In [30]:
# Get a default graph
graph_1 = tf.get_default_graph()

In [34]:
# Create a new graph
graph_2 = tf.Graph()

In [38]:
# to set graph_2 as default graph
with graph_2.as_default():
  print(graph_2)
  print(graph_2 is tf.get_default_graph())# to check whether the graph_2 is set to default graph

True


# BUT, it is to be noted that the above will work under local scope. If you try to print this in a global level then we will again have graph_1 as the default graph.

In [40]:

# Lets check this out
graph_1 is get_default_graph()

True

# There are two main tensor objects in a graph- variables and placeholders

In [46]:
# create a tensor
new_tensor = tf.random_normal((4,4))

In [47]:
sess.run(new_tensor)

array([[-0.44383726,  0.9842642 ,  0.89496213, -0.36507675],
       [ 0.17152528,  1.6601074 ,  0.7698097 , -0.7437338 ],
       [-0.03852652,  1.052567  , -0.19112135,  0.69622034],
       [ 0.5552106 ,  0.5089329 ,  1.1286408 , -1.3035915 ]],
      dtype=float32)

In [52]:
# CREATE A VARIABLE
new_variable = tf.Variable(initial_value=new_tensor)

# If you try run the variable with sess.run(new_variable) we will get an error - FailedPreconditionError
# This is because we need to initialize the variable

In [54]:
# initilizing function
init = tf.global_variables_initializer()

In [56]:
# run the initilization
sess.run(init)

In [58]:
# Try to run the variable
sess.run(new_variable)

array([[-1.0757754 , -1.3182123 ,  0.24291566,  0.8178238 ],
       [ 0.6927579 ,  1.149549  , -1.5985435 ,  0.36982876],
       [ 0.523105  ,  0.3340683 ,  0.31818643, -0.34429303],
       [-0.80809456, -1.0003623 ,  0.8651219 , -0.06896771]],
      dtype=float32)

In [61]:
# create a placeholder
new_placeholder = tf.placeholder(tf.float32, shape=(4,4))

In [62]:
new_placeholder

<tf.Tensor 'Placeholder_1:0' shape=(4, 4) dtype=float32>

# Mostly the shape in placeholder will be None,some number as we weill train the model in batches and we dont know prior the shape of the training set data.

In [63]:
# create a new placeholder
new_placeholder_2 = tf.placeholder(tf.float32, shape=(None,4))

In [64]:
new_placeholder_2

<tf.Tensor 'Placeholder_2:0' shape=(?, 4) dtype=float32>